language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - travis_retry pip install python-coveralls nose-cov
  - python setup.py install

# Run test
script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; nosetests -v --with-cov --cov chardet --cov-config .coveragerc --logging-level=DEBUG
  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; nosetests -v --logging-level=DEBUG

# Calculate coverage
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; coveralls --config_file .coveragerc

notifications:
  email:
    on_success: change
    on_failure: always
